linux: &linux
   os: linux
   sudo: required
   language: python
   python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
      - <<: *osx
        osx_image: xcode9

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
