linux: &linux
  os: linux
  sudo: required
  language: python

osx: &osx
  os: osx
  language: generic
  osx_image: xcode9

addons:
  apt:
    packages:
      - python3
      - python3-dev

matrix:
  include:
    - <<: *linux
      env: PYEXEC=python CONAN_OPTIONS=python_dev_config:python=python
    - <<: *linux
      env: PYEXEC=python3 CONAN_OPTIONS=python_dev_config:python=python3
    - <<: *osx
      env: PYEXEC=python CONAN_OPTIONS=python_dev_config:python=python

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
